application: clementine-player
version: dev
runtime: python
api_version: 1

inbound_services:
- xmpp_message

handlers:
- url: /css
  static_dir: static/css

- url: /images
  static_dir: static/images

- url: /favicon.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /_tasks/.*
  script: tasks.py
  login: admin

- url: /projects.*
  script: projects.py

- url: /versions
  script: clementine.py
  login: admin

- url: /sparkle
  script: clementine.py

- url: /sparkle-windows
  script: clementine.py

- url: /rainymood
  script: clementine.py

- url: /
  script: projects.py

- url: /c2dm/.*
  script: c2dm.py
  secure: always
  login: required

- url: /.*
  script: clementine.py
