application: clementine-crashes-hrd
version: dev
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
- url: /getuploadurl
  script: upload.app

- url: /upload/.*
  script: upload.app

- url: /_uploadhandler/.*
  script: upload.app


- url: /symbolcheck
  script: download.app

- url: /symbols/.*
  script: download.app


- url: /rawcrash/.*
  script: processing.app

- url: /processcrash/.*
  script: processing.app


- url: /crashes.*
  script: crashes.app

- url: /crash/.*
  script: crashes.app


- url: /static
  static_dir: static
  expiration: "7d"


- url: /.*
  script: index.app
