application: clementine-crashes-hrd
version: dev
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest

handlers:
# Deprecated URL used by old versions of Clementine.
- url: /getuploadurl
  script: upload.app

# Used when uploading crashes and symbols.
- url: /upload/.*
  script: upload.app

- url: /_uploadhandler/.*
  script: upload.app

# Used by the crash processor.
- url: /symbolcheck
  script: download.app

- url: /symbols/.*
  script: download.app

- url: /rawcrash/.*
  script: processing.app

- url: /processcrash/.*
  script: processing.app

# Static content.
- url: /static
  static_dir: static
  expiration: "7d"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# Public UI.
- url: /crash/.*
  script: crashes.app

- url: /
  script: crashes.app
