application: clementine-crashes-hrd
version: dev
runtime: python27
api_version: 1
threadsafe: true

libraries:
- name: jinja2
  version: latest
- name: pycrypto
  version: latest

handlers:
# Deprecated URL used by old versions of Clementine.
- url: /getuploadurl
  script: upload.app

# New API
- url: /api/upload/symbols
  script: symbols.app

- url: /api/upload/minidump
  script: minidumps.app

- url: /api/upload/crashreport
  script: minidumps.app

# Static content.
- url: /static
  static_dir: static
  expiration: "7d"

- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# Public UI.
- url: /crash/.*
  script: crashes.app

- url: /
  script: crashes.app
